Repository cmns-nl/.framework, pull requests merged in 2021-11, with the labels that each got.

#30 removed log() shortcut
  boilerplate_app.py
Labels: bug

#31 Improved inline documentation as issue #17
  boilerplate_common.py
Labels: documentation

#32 removed old log shortcut as it is obsolete
  boilerplate_framework.py
Labels: Cleanup

#33 Improved readme, added requirements and installation instructions
  README.md
Labels: documentation

#34 Included configuration in README
  README.md
Labels: documentation

#35 included toc in readme
  README.md
Labels: documentation, enhancement

#37 Several small fixes
  boilerplate_app.py
  boilerplate_framework.py
  framework_core.py
Labels: Improvement

#39 Added --yes to readme documentation
  README.md
Labels: documentation

#40 Renamed repository to cmns-nl
  README.md
  boilerplate_app.py
  boilerplate_common.py
Labels: enhancement

#41 fixed issue in installation documentation
  README.md
Labels: bug, documentation

#43 Added shortcut to argparse object for easier access to add_argument
  boilerplate_common.py
Labels: enhancement
